# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Test ÉAM(376dbbee-bcac-4d7a-98f0-fb6216a0cfc1)'
    subscriptionId: '376dbbee-bcac-4d7a-98f0-fb6216a0cfc1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'POC_LogAnalytics'
    location: 'Canada Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/arthurdelduque/AzureRmPipeline-repo/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName myarmpipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'